// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// stabest_internal
List stabest_internal(Rcpp::NumericVector Vc, Rcpp::NumericVector Vs, arma::sp_mat Xc, arma::sp_mat XcXcInv, arma::sp_mat Xs, arma::sp_mat XsXsInv, Rcpp::NumericMatrix betaR, Rcpp::NumericMatrix gammaR, Rcpp::LogicalVector VacantSeats, Rcpp::IntegerVector nObs_college, Rcpp::IntegerVector ID_eqCollege, Rcpp::LogicalVector match, Rcpp::IntegerVector sid, Rcpp::IntegerVector ID_cBetter, Rcpp::IntegerVector ID_cWorse, Rcpp::IntegerVector ID_sBetter, Rcpp::IntegerVector ID_sWorse, Rcpp::IntegerVector ID_nextCollege, int niter, int thin, int demean);
RcppExport SEXP _stabest_stabest_internal(SEXP VcSEXP, SEXP VsSEXP, SEXP XcSEXP, SEXP XcXcInvSEXP, SEXP XsSEXP, SEXP XsXsInvSEXP, SEXP betaRSEXP, SEXP gammaRSEXP, SEXP VacantSeatsSEXP, SEXP nObs_collegeSEXP, SEXP ID_eqCollegeSEXP, SEXP matchSEXP, SEXP sidSEXP, SEXP ID_cBetterSEXP, SEXP ID_cWorseSEXP, SEXP ID_sBetterSEXP, SEXP ID_sWorseSEXP, SEXP ID_nextCollegeSEXP, SEXP niterSEXP, SEXP thinSEXP, SEXP demeanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Vc(VcSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Vs(VsSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Xc(XcSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type XcXcInv(XcXcInvSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type Xs(XsSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type XsXsInv(XsXsInvSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type betaR(betaRSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gammaR(gammaRSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type VacantSeats(VacantSeatsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type nObs_college(nObs_collegeSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ID_eqCollege(ID_eqCollegeSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type match(matchSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sid(sidSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ID_cBetter(ID_cBetterSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ID_cWorse(ID_cWorseSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ID_sBetter(ID_sBetterSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ID_sWorse(ID_sWorseSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type ID_nextCollege(ID_nextCollegeSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type demean(demeanSEXP);
    rcpp_result_gen = Rcpp::wrap(stabest_internal(Vc, Vs, Xc, XcXcInv, Xs, XsXsInv, betaR, gammaR, VacantSeats, nObs_college, ID_eqCollege, match, sid, ID_cBetter, ID_cWorse, ID_sBetter, ID_sWorse, ID_nextCollege, niter, thin, demean));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_stabest_stabest_internal", (DL_FUNC) &_stabest_stabest_internal, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_stabest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
